#!/bin/bash

if type node >/dev/null 2>&1 && which node >/dev/null 2>&1; then
  echo "node is installed, skipping..."
else
  echo "install node"
  # Set Node globally
  echo "Set Node globally"
  n=$(which node)
  n=${n%/bin/node}
  sudo chmod -R 755 $n/bin/*
  sudo cp -r $n/{bin,lib,share} /usr/local
  which node
fi

echo "Check Node Version"
node -v

echo "Check NPM Version"
npm -v

echo "Check Yarn Version"
yarn --version
