#!/bin/bash

if type node >/dev/null 2>&1 && which node >/dev/null 2>&1; then
  echo "node is installed, skipping..."
else
  echo "install node"

  # START UBUNTU USERSPACE
  echo "==================================="
  echo "Installing NVM"
  echo "==================================="
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.9/install.sh | bash
  echo 'export NVM_DIR="/home/ubuntu/.nvm"' >>/home/ubuntu/.bashrc
  echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm' >>/home/ubuntu/.bashrc

  # Dot source the files to ensure that variables are available within the current shell
  . /home/ubuntu/.nvm/nvm.sh
  . /home/ubuntu/.profile
  . /home/ubuntu/.bashrc

  echo "Installing NodeJS 16.20.1"
  nvm list-remote

  echo "Install Node 16.20.1"
  nvm install 16.20.1
  nvm use 16.20.1

  echo "Check Node Version"
  node -v
  echo "Check NPM Version"
  npm -v

  # Install Yarn
  echo "==================================="
  echo "Install Yarn"
  echo "==================================="
  npm install --global yarn

  echo "Check Yarn Version"
  yarn --version

  # Install Pm2
  echo "==================================="
  echo "Install PM2"
  echo "==================================="
  echo "Installing PM2"
  npm install pm2@latest -g
  pm2 startup systemd
  echo "Check PM2 Version"
  pm2 --version

  # Set Node globally
  echo "Set Node globally"
  n=$(which node)
  n=${n%/bin/node}
  sudo chmod -R 755 $n/bin/*
  sudo cp -r $n/{bin,lib,share} /usr/local
  which node
fi

echo "Check Node Version"
node -v

echo "Check NPM Version"
npm -v

echo "Check Yarn Version"
yarn --version
