#!/bin/bash
sudo apt update
sudo apt autoremove

sudo n=$(which node);n=${n%/bin/node}; sudo chmod -R 755 $n/bin/*; sudo cp -r $n/{bin,lib,share} /usr/local

node -v
npm -v
yarn --version

cd /home/ubuntu/project/node-js-demo

npm install

pm2 flush
