version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/project/node-js-demo/
    overwrite: true
    file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: aws-script/install_dependencies
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: aws-script/start_server
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: aws-script/stop_server
      timeout: 300
      runas: ubuntu
