version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/project/node-js-demo/
    overwrite: true
    file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: aws-script/ApplicationStop
      timeout: 300
      runas: root
  DownloadBundle:
    - location: aws-script/DownloadBundle
      timeout: 300
      runas: root
  BeforeInstall:
    - location: aws-script/BeforeInstall
      timeout: 300
      runas: root
  Install:
    - location: aws-script/Install
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws-script/AfterInstall
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws-script/ApplicationStart
      timeout: 300
      runas: root
