version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: aws-script/install_dependencies
      timeout: 300
      runas: root
    - location: aws-script/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: aws-script/stop_server
      timeout: 300
      runas: root
